packages:
  - 'apps/*'
  - 'packages/*'
  - 'tests/*'

catalog:
  '@types/node': ^20.0.0
  '@powerbase/auth-js': ^2.71.3
  '@skorpland/powerbase-js': ^2.51.5
  '@powerbase/realtime-js': ^2.11.7
  next: ^14.2.26
