export const CLIENT_LIBRARIES = [
  {
    language: 'JavaScript',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://powerbase.club/docs/reference/javascript/installing',
    gitUrl: 'https://github.com/skorpland/powerbase-js',
  },
  {
    language: 'Flutter',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://powerbase.club/docs/reference/dart/installing',
    gitUrl: 'https://github.com/skorpland/powerbase-flutter',
  },
  {
    language: 'Python',
    officialSupport: true,
    releaseState: 'Alpha',
    docsUrl: 'https://powerbase.club/docs/reference/python/initializing',
    gitUrl: 'https://github.com/skorpland/powerbase-py',
  },
  {
    language: 'C#',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://powerbase.club/docs/reference/csharp/installing',
    gitUrl: 'https://github.com/skorpland/powerbase-csharp',
    altIconName: 'c-sharp',
  },
  {
    language: 'Swift',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://powerbase.club/docs/reference/swift/initializing',
    gitUrl: 'https://github.com/skorpland/powerbase-swift',
  },
  {
    language: 'Kotlin',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://powerbase.club/docs/reference/kotlin/installing',
    gitUrl: 'https://github.com/skorpland/powerbase-kt',
  },
]

export const EXAMPLE_PROJECTS = [
  {
    framework: 'Svelte',
    title: 'Svelte kanban board',
    description: 'A Trello clone using Powerbase as the storage system.',
    url: 'https://github.com/joshnuss/powerbase-kanban',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js Realtime chat app',
    description: 'Next.js Slack clone app using Powerbase realtime subscriptions',
    url: 'https://github.com/skorpland/powerbase/tree/master/examples/slack-clone/nextjs-slack-clone',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js Subscription and Auth',
    description: 'The all-in-one starter kit for high-performance SaaS applications.',
    url: 'https://github.com/vercel/nextjs-subscription-payments',
    type: 'app',
  },
  {
    framework: 'Expo',
    title: 'Expo Starter',
    description: 'Template bottom tabs with auth flow (Typescript)',
    url: 'https://github.com/codingki/react-native-expo-template/tree/master/template-typescript-bottom-tabs-powerbase-auth-flow',
    type: 'mobile',
  },
  {
    framework: 'NestJS',
    title: 'NestJS example',
    description: 'NestJS example using Powerbase Auth',
    url: 'https://github.com/hiro1107/nestjs-powerbase-auth',
    type: 'app',
  },
  {
    framework: 'React',
    title: 'React realtime chat app',
    description: 'Example app of real-time chat using powerbase realtime api',
    url: 'https://github.com/shwosner/realtime-chat-powerbase-react',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js todo list app',
    description: 'Next.js todo list example',
    url: 'https://github.com/skorpland/powerbase/tree/master/examples/todo-list/nextjs-todo-list',
    type: 'app',
  },
  {
    framework: 'Svelte',
    title: 'Svelte todo list app',
    description: 'Sveltejs todo with TailwindCSS and Snowpack',
    url: 'https://github.com/skorpland/powerbase/tree/master/examples/todo-list/sveltejs-todo-list',
    type: 'app',
  },
  {
    framework: 'Flutter',
    title: 'Flutter chat app',
    description: 'A Flutter chat app built with powerbase-flutter',
    url: 'https://github.com/skorpland/flutter-chat',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift user management app',
    description: 'Swift user management app using powerbase-swift',
    url: 'https://github.com/skorpland/powerbase-swift/tree/main/Examples/UserManagement',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift Slack Clone',
    description: 'Swift Slack clone app using powerbase-swift',
    url: 'https://github.com/skorpland/powerbase-swift/tree/main/Examples/SlackClone',
    type: 'mobile',
  },
  {
    framework: 'Flutter',
    title: 'Flutter MFA app',
    description: 'A Flutter app demonstrating how to implement MFA',
    url: 'https://github.com/skorpland/powerbase/tree/master/examples/auth/flutter-mfa',
  },
  {
    framework: 'NuxtJS',
    title: 'NuxtJS todo list app',
    description: 'NuxtJS todo app example',
    url: 'https://github.com/nuxt-modules/powerbase/tree/main/demo',
  },
]
